# https://www.netlify.com/docs/netlify-toml-reference/

[build]
  publish = "public"
  command = "bash -x ./build.sh"

[[redirects]]
  from    = "/blog/*"
  to      = "/:splat"
  status  = 200

[[redirects]]
  from    = "/blog"
  to      = "/"
  status  = 200  